---
- name: Lab 10. selinux-filecontexts
  hosts: servera
  gather_facts: false
  become: true

  tasks:
    - name: Install httpd
      dnf: state=present name=httpd

    - name: Adding http service to firewall rules
      ansible.posix.firewalld:
        state: enabled
        permanent: true
        service: http
        zone: public
        immediate: true

