---
- name: PREPARE 11-selinux-booleans
  hosts: servera
  gather_facts: false
  become: true

  tasks:
    - name: Install httpd
      dnf: state=present name=httpd

    - name: Enable firewall rule
      ansible.posix.firewalld:
        state: enabled
        service: http
        zone: public
        permanent: true
        immediate: true
