---
- name: Provision VM
  hosts: lab
  become: true
  gather_facts: false

  vars:
    ansible_user: vagrant
    ansible_ssh_private_key_file: ~/.vagrant.d/insecure_private_key

  tasks:
    - name: Create student user on workstation server
      user:
        name: student
        password: "$1$IGBfzAun$cxL63lmjRG/m7xZBgx4IX/"

    - name: Ensure that .ssh exists under student home
      file:
        state: directory
        path: /home/student/.ssh
        mode: 0700
        owner: student
        group: student

    - name: Copy id_rsa to workstation
      copy:
        src: "{{ ansible_ssh_private_key_file }}"
        dest: /home/student/.ssh/id_rsa
        owner: student
        group: student
        mode: 0600
      run_once: true
      delegate_to: workstation

    - name: Copy vagrant authorized_keys to student user
      copy:
        src: /home/vagrant/.ssh/authorized_keys
        dest: /home/student/.ssh/
        owner: student
        group: student
        mode: 0600
        remote_src: true

    - name: Add hosts in hosts file 
      blockinfile:
        path: /etc/hosts
        block: |
          172.25.250.9   workstation.lab.example.com  workstation
          172.25.250.10  servera.lab.example.com  servera
          172.25.250.11  serverb.lab.example.com  serverb
        marker: ""

    - name: Add sudo permission to student
      lineinfile:
        path: /etc/sudoers.d/student
        state: present
        line: "student ALL=(ALL) ALL"
        create: true

    - name: Install SELinux utils
      dnf: state=present name={{ item }}
      loop: 
        - policycoreutils-python-utils
        - setroubleshoot-server
    
    - name: Enable and start setroubleshootd
      service: state=started enabled=true name=setroubleshootd
