---
- name: Prepare lab. 1 SSH key
  hosts: servera,serverb
  gather_facts: false
  become: true
  
  tasks:
    - name: Delete user operator1
      user: state=absent name=operator1 remove=true

    - name: Disable password access
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "PasswordAuthentication yes"
        line: "PasswordAuthentication no"
        backrefs: true

    - name: Restart ssh service
      service: name=sshd state=restarted
