---
- name: Check lab 3. files-review
  hosts: servera
  gather_facts: false
  become: true
  become_user: student

  tasks:
    - name: Delete files
      file: state=absent path={{ item }}
      loop: 
        - /home/student/Documents
        - /home/student/Videos
