---
- name: END 11-selinux-booleans
  hosts: servera
  gather_facts: false
  become: true

  tasks:
    - name: Remove httpd package
      dnf: state=absent name=httpd

    - name: Remove firewall rule
      ansible.posix.firewalld:
        state: disabled
        service: http
        zone: public
        permanent: true
        immediate: true

    - name: Reset home permissions
      file: path=/home/student mode=0700

    - name: Remove public_html
      file: state=absent path=/home/student/public_html

    - name: Reset SELinux boolean
      command: "setsebool -P httpd_enable_homedirs=off"

