---
- name: CHECK 05-users-password
  hosts: servera
  gather_facts: false
  become: true

  tasks:
    - name: Get all password info
      command: chage -li operator1
      register: chage

    - name: Get PASS_MAX_DAYS from /etc/login.defs
      slurp: src=/etc/login.defs
      register: login_defs  

    - name: Get expiring date
      command: date -d "+180 days" "+%F"
      register: expiring_date
        
    - name: Assert chage requirements
      assert:
        that:
          - "account_expire == expiring_date.stdout"
          - "(maximum_pwd_change | int) == 90"
        fail_msg: "LAB FAILED: Error during password configuration"
        quiet: true
      vars:
        account_expire: "{{ chage.stdout | regex_search('Account expires.*', multiLine=true) | split(': ') | last }}"
        maximum_pwd_change: "{{ chage.stdout | regex_search('Maximum number of days between password change.*', multiLine=true) | split(': ') | last }}"

    - name: Assert login.defs config
      assert:
        that: 
          - "pass_max_days == '180'"
        fail_msg: "LAB FAILED: Error during /etc/login.defs configuration"
        quiet: true
      vars:
        pass_max_days: "{{ login_defs.content | b64decode | regex_search('\nPASS_MAX_DAYS.*', multiLine=true) | split('\t') | last }}"
