---
- name: CHECK 15-processes-monitor
  hosts: servera
  gather_facts: false
  become: true
  become_user: student

  tasks:
    - name: Get all processes
      command: "ps -a"
      register: student_processes

    - name: Assert monitor processes
      assert:
        that:
          - "monitor == '0'"
        fail_msg: "LAB FAILED: monitor processes exists"
        quiet: true
      vars:
        monitor: "{{ student_processes.stdout_lines | select('match', '.*monitor.*') | length }}"
